# Generated by Django 5.0.4 on 2024-06-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_lote', models.CharField(max_length=100)),
                ('qtde_inicial', models.IntegerField()),
                ('qtde_ativa', models.IntegerField()),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockflow.produto')),
            ],
        ),
    ]
